version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: wxdump
    binary: wxdump
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }}"

archives:
  - ids: [wxdump]
    formats: [binary]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
